# Generated by Django 5.0.2 on 2024-03-02 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('DEV', 'Development'), ('SAL', 'Sales'), ('FIN', 'Finance'), ('HR', 'HR'), ('INS', 'Installation')], max_length=3)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('estimation_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignee', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
